name: Connector Publish workflow

permissions: read-all

on:
  workflow_call:
    inputs:
      package-name:
        required: true
        type: string
      branch:
        type: string
        default: "main"
      rust-profile:
        type: string
        default: "release"
      cloud-url:
        type: string
      fail-fast:
        type: boolean
        default: true
      readme:
        type: string
        default: "./README.md"
      public:
        type: boolean
        default: true
    secrets:
      FLUVIO_CONFIG:
        required: true
      FLUVIO_HUB_DEFAULT:
        required: true
      FLUVIO_LOGINS_KEY:
        required: true
      FLUVIO_LOGINS_CONTENT:
        required: true

jobs:
  linux:
    name: linux
    runs-on: ubuntu-latest
    strategy:
      fail-fast: ${{ inputs.fail-fast }}
      matrix:
        rust-target:
          [
            aarch64-unknown-linux-musl,
            aarch64-unknown-linux-gnu,
            x86_64-unknown-linux-musl,
            x86_64-unknown-linux-gnu,
          ]
    env:
      CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse
    steps:
      - name: Setup Fluvio
        uses: infinyon/fluvio/.github/actions/setup-fluvio@master
      - name: Fluvio Login
        run: |
          mkdir -p ~/.fluvio
          cat <<EOF > ~/.fluvio/config
          ${{ secrets.FLUVIO_CONFIG }}
          EOF
          mkdir -p ~/.fluvio/hub
          cat <<EOF > ~/.fluvio/hub/default
          ${{ secrets.FLUVIO_HUB_DEFAULT }}
          EOF
          echo -n "default" > ~/.fluvio/hub/hcurrent
          mkdir -p ~/.fluvio/logins
          cat <<EOF > ~/.fluvio/logins/"${{ secrets.FLUVIO_LOGINS_KEY }}"
          ${{ secrets.FLUVIO_LOGINS_CONTENT }}
          EOF
          echo -n "${{ secrets.FLUVIO_LOGINS_KEY }}" > ~/.fluvio/logins/current
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
      - uses: Swatinem/rust-cache@v2
        with:
          cache-targets: "false"
          cache-on-failure: "true"
      - name: Install Cross
        run: cargo install cross
      - name: Build
        run: |
          cross build --profile ${{ inputs.rust-profile }}  --target ${{ matrix.rust-target }} -p ${{ inputs.package-name }}
      - name: Publish
        run: |
          cdk publish --no-build \
            ${{ inputs.public && '--public-yes' || '' }} \
            --target ${{ matrix.rust-target }} \
            -p ${{ inputs.package-name }} \
            --readme ${{ inputs.readme }}

  macos:
    name: macos
    runs-on: macos-latest
    strategy:
      fail-fast: ${{ inputs.fail-fast }}
      matrix:
        rust-target: [x86_64-apple-darwin, aarch64-apple-darwin]
    env:
      CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse
    steps:
      - name: Setup Fluvio
        uses: infinyon/fluvio/.github/actions/setup-fluvio@master
      - name: Fluvio Login
        run: |
          mkdir -p ~/.fluvio
          cat <<EOF > ~/.fluvio/config
          ${{ secrets.FLUVIO_CONFIG }}
          EOF
          mkdir -p ~/.fluvio/hub
          cat <<EOF > ~/.fluvio/hub/default
          ${{ secrets.FLUVIO_HUB_DEFAULT }}
          EOF
          echo -n "default" > ~/.fluvio/hub/hcurrent
          mkdir -p ~/.fluvio/logins
          cat <<EOF > ~/.fluvio/logins/"${{ secrets.FLUVIO_LOGINS_KEY }}"
          ${{ secrets.FLUVIO_LOGINS_CONTENT }}
          EOF
          echo -n "${{ secrets.FLUVIO_LOGINS_KEY }}" > ~/.fluvio/logins/current
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
      - uses: Swatinem/rust-cache@v2
        with:
          cache-targets: "false"
          cache-on-failure: "true"
      - name: Build
        run: |
          rustup target add ${{ matrix.rust-target }}
          cargo build --profile ${{ inputs.rust-profile }}  --target ${{ matrix.rust-target }} -p ${{ inputs.package-name }}
      - name: Publish
        run: |
          cdk publish ${{ inputs.public && '--public-yes' || '' }} \
            --target ${{ matrix.rust-target }} \
            -p ${{ inputs.package-name }} \
            --readme ${{ inputs.readme }}
