name: Publish Hub

permissions: read-all

on:
  push:
    tags:
      - v*
  workflow_dispatch:
    inputs:
      branch:
        description: "The branch, tag or SHA to checkout"
        required: true
        type: string
        default: "main"

jobs:
  publish:
    uses: ./.github/workflows/connector-publish.yml
    with:
      package-name: http-source
      branch: ${{ github.event.inputs.branch }}
      fail-fast: false
      readme: ./README.md
    secrets:
      FLUVIO_CONFIG: ${{ secrets.FLUVIO_CONFIG }}
      FLUVIO_HUB_DEFAULT: ${{ secrets.FLUVIO_HUB_DEFAULT }}
      FLUVIO_LOGINS_KEY: ${{ secrets.FLUVIO_LOGINS_KEY }}
      FLUVIO_LOGINS_CONTENT: ${{ secrets.FLUVIO_LOGINS_CONTENT }}
